workflows:
  CodemagicCICDiOS-workflow:
    name: CodemagicCICD
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        BUNDLE_ID: "com.fz.codemagiccicd"
        XCODE_PROJECT: "CodemagicCICD/CodemagicCICD.xcodeproj"
        XCODE_SCHEME: "CodemagicCICD"
      xcode: latest
    scripts:
      - name: iOS test
        script: |
          xcode-project run-tests \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"
            --device "iPhone 15"
        test_report: build/ios/test/*.xml
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
