workflows:
  CodemagicCICDiOS-workflow:
    name: CodemagicCICD
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        BUNDLE_ID: "com.fz.codemagiccicd"
        XCODE_PROJECT: "CodemagicCICD/CodemagicCICD.xcodeproj"
        XCODE_SCHEME: "CodemagicCICD"
      xcode: latest

